apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-cfg
data:
  envoy.conf: |
static_resources:
  listeners:
  - address:
      socket_address: 0.0.0.0
      port_value: 80
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: default
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: default-cluster
          http_filters:
          - name: envoy.filters.http.router
  clusters:
  - name: default-cluster
    connect_timeout: 15s
    type: strict_dns
    http_protocol_options: {}
    load_assignment:
      cluster_name: keycloak-backend
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: svc-apache.default.svc.cluster.local
                port_value: 80
  admin:
    access_log_path: /dev/null
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 8001
