apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cfg
data:
  nginx.conf: |
    server {
      listen 80;
      location / {
        proxy_pass http://svc-apache.default.svc.cluster.local:80;
      }
    }
